### ISSUE TITLE
Error: getaddrinfo ENOTFOUND tokenmapper.api.matic.today

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/evm-token-list#1]
Latest CI failed:

https://github.com/sablier-labs/community-token-list/actions/runs/5325410111/jobs/9646074418

**Comment by maxdesalle** [comment]
Apologies, seems like I missed this issue @PaulRBerg. Seems like the issue is happening [here](https://github.com/sablier-labs/community-token-list/blob/266d613dd3c7d3de48d0034f8885429d6a2efe5f/src/buildList.js#L51)? Not sure what is actually going wrong, the error message isn't very helpful, unfortunately.

Any idea what the issue might be @razgraf?

**Comment by maxdesalle** [comment]
Fixed in [b286908](https://github.com/sablier-labs/community-token-list/commit/b2869084bd305a9c2b5218844027ca88eabcb52f).
